log:
  level: info
  file: "/var/log/forgedns.log"

api:
  http: 172.16.2.53:9199


plugins:
  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/opt/forgedns/rule/whitelist.txt"
        - "/opt/forgedns/dat/geosite_cn.txt"
        - "/opt/forgedns/dat/geosite_apple-cn.txt"
        - "/opt/forgedns/dat/geosite_apple.txt"
        - "/opt/forgedns/dat/geosite_category-games@cn.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/opt/forgedns/rule/greylist.txt"
        - "/opt/forgedns/dat/geosite_geolocation-!cn.txt"

  # hosts
  - tag: hosts
    type: hosts
    args:
      files:
        - "/opt/forgedns/rule/hosts.txt"


  # 国内IP
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        # 运营商dns
        - addr: "61.139.2.69"
        # 运营商dns
        - addr: "218.6.200.139"
        - addr: "223.5.5.5"

  # 转发至国外DNS, 并发查询
  - tag: forward_remote
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://1.1.1.1/dns-query"
          socks5: "172.16.2.40:7890"
        - addr: "https://8.8.8.8/dns-query"
          socks5: "172.16.2.40:7890"

  # fallback服务器, 返回国内ip则accept, 返回非国内ip则drop
  - tag: local_sequence
    type: sequence
    args:
      - exec: $cache
      - exec: $forward_local

  - tag: cache
    type: cache
    args:
      size: 5120
      dump_file: cache.dump
      short_circuit: true
    

 # 动态路由 添加解析后的ip到
  - tag: mikrotik 
    type: mikrotik
    args:
      address: 172.16.1.1:8728
      username: api_user
      password: secret
      address_list4: proxy_dst
      comment_prefix: fdns
      min_ttl: 600
      persistent:
        files:
          - "/opt/forgedns/dat/geoip_telegram.txt"

  # fallback的secondary服务器, 返回非国内ip则添加至ipset, 返回国内ip只接受不会添加ipset 解析后将ip添加到路由中
  - tag: remote_sequence
    type: sequence
    args:
      - exec: $mikrotik
      - exec: $cache
      - exec: $forward_remote


  # fallback sequence
  - tag: fallback
    type: fallback
    args:
      primary: remote_sequence
      secondary: local_sequence
      threshold: 500
      always_standby: true

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - matches: 
        - has_resp
        exec: accept

  - tag: query
    type: sequence
    args:
      - matches:
        - qname $geosite_cn
        exec: $forward_local
      - exec: jump has_resp_sequence

      - exec: $remote_sequence
      - exec: jump has_resp_sequence

      - exec: $fallback
      - exec: jump has_resp_sequence
      - exec: reject 3

      

  - tag: main_sequence
    type: sequence
    args:
      # hosts
      - exec: $hosts
      - matches: has_resp
        exec: accept
      # 主入口
      - exec: $query
    
  
  - tag: "udp_server"
    type: "udp_server"
    args: 
      entry:  "main_sequence"
      listen:  "0.0.0.0:5335"
  
  - tag: "tcp_server"
    type: "tcp_server"
    args: 
      entry:  "main_sequence"
      listen:  "0.0.0.0:5335"
